### ISSUE TITLE
docs: Add a code of conduct

### ISSUE THREAD

**Issue by BekahHW** [jasonetorres/pizzapics#13]
# Issue Template for PizzaPix

## Description

Right now, there's not a COC, and it can help build a safe environment for both the contributors and maintainers.

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Environment

- **Operating System:**
- **Browser (if applicable):**
- **Node.js version:**
- **NPM version:**
- **Tailwind CSS version:**
- **Other relevant dependencies and their versions:**

## Additional Information

---

### Contributor Checklist

- [x] I have searched for similar issues and confirmed this is not a duplicate.
- [x] I have provided a clear and concise description of the issue.
- [x] I have included all necessary steps to reproduce the issue.
- [ ] I have attached relevant screenshots (if applicable).
- [ ] I have filled out the environment section with accurate details.

**Comment by jasonetorres** [comment]
great addition! thanks for bringing this to our attention!
