### ISSUE TITLE
Property 'id' does not exist on type '{}'.

### ISSUE THREAD

**Issue by jasonetorres** [jasonetorres/pizzapics#16]
interface UserAccountDetails {
[$id](https://twitter.com/search?q=%24id&src=cashtag_click): string;
name: string;
email: string;
username?: string;
}

// ==== SIGN UP
export async function createUserAccount(user: INewUser) {
try {
const { email, password, name, username } = user;

const [$id](https://twitter.com/search?q=%24id&src=cashtag_click) = ID.unique();
const newAccount: UserAccountDetails = await account.create(
[$id](https://twitter.com/search?q=%24id&src=cashtag_click),
email,
password,
name
);

if (!newAccount) throw Error;

const avatarUrl = avatars.getInitials([http://user.name](https://t.co/SCOt0iFKG2));

const newUser = await saveUserToDB({
accountID: [$id](https://twitter.com/search?q=%24id&src=cashtag_click),
name,
email,
username,
imageUrl: avatarUrl,
});

return newUser;
} catch (error) {
console.log(error);
return error;
}
}

**Comment by shookcodes** [comment]
PR submitted for issue:
https://github.com/jasonetorres/pizzapics/pull/17

**Comment by jasonetorres** [comment]
great work Sarah

**Comment by jasonetorres** [comment]
set
